#!/usr/bin/env python3
"""Pre-generates card/thumbnail WebP versions of every R2 image referenced by the
storefront's hardcoded catalog data (js/catalog.js and friends), so those pages never
resize an image at request time - not via a third-party proxy (images.weserv.nl, now
removed) and not via a self-hosted redirect endpoint either. Everything happens once,
here, with Pillow (via backend/app/services/storage.get_or_create_thumbnail, the same
function catalog.py's server-rendered pages call in-process).

Output is js/shared/thumb-map.js, a plain `window.THUMB_MAP = {...}` object mapping
each original R2 url to its cached thumbnail url. Each page's cldOpt() does a
synchronous lookup into that map - zero network hop, zero runtime image processing.

Reads R2_* from backend/.env (same as every other scripts/*.py). Safe to re-run:
get_or_create_thumbnail() is itself idempotent (head_object check before regenerating),
so this only does real work for images that are new since the last run.

Usage:
    python scripts/generate_thumbnails.py [--width 640] [--quality 75]
"""
import argparse
import json
import os
import re
import sys
from pathlib import Path

from dotenv import load_dotenv

ROOT = Path(__file__).resolve().parent.parent
BACKEND_DIR = ROOT / "backend"
load_dotenv(BACKEND_DIR / ".env")
os.environ.setdefault("DATABASE_URL", "postgresql://unused:unused@localhost/unused")

sys.path.insert(0, str(BACKEND_DIR))
from app.services.storage import get_or_create_thumbnail, storage_configured  # noqa: E402

OUT_PATH = ROOT / "js" / "shared" / "thumb-map.js"
URL_RE = re.compile(r"https://[a-zA-Z0-9.-]+\.r2\.dev/[^\s\"'`)]+?\.(?:jpg|jpeg|png|webp|gif|avif)", re.IGNORECASE)

TARGET_GLOBS = ["js/*.js", "js/shared/*.js"]


def find_urls() -> list[str]:
    urls: set[str] = set()
    for glob_pattern in TARGET_GLOBS:
        for path in sorted(ROOT.glob(glob_pattern)):
            if path.resolve() == OUT_PATH.resolve():
                continue
            text = path.read_text(encoding="utf-8")
            urls.update(m.group(0) for m in URL_RE.finditer(text))
    return sorted(urls)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--width", type=int, default=640)
    parser.add_argument("--quality", type=int, default=75)
    args = parser.parse_args()

    if not storage_configured():
        print("R2 isn't configured (check backend/.env) - nothing to do.", file=sys.stderr)
        sys.exit(1)

    urls = find_urls()
    print(f"Found {len(urls)} unique R2 image URL(s) across {', '.join(TARGET_GLOBS)}")

    thumb_map: dict[str, str] = {}
    if OUT_PATH.exists():
        existing = OUT_PATH.read_text(encoding="utf-8")
        m = re.search(r"window\.THUMB_MAP\s*=\s*(\{.*\});", existing, re.DOTALL)
        if m:
            thumb_map = json.loads(m.group(1))

    failures = []
    for i, url in enumerate(urls, 1):
        thumb_url = get_or_create_thumbnail(url, width=args.width, quality=args.quality)
        if thumb_url:
            thumb_map[url] = thumb_url
            print(f"[{i}/{len(urls)}] ok   {url}")
        else:
            failures.append(url)
            print(f"[{i}/{len(urls)}] FAIL {url}")

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(
        "// Auto-generated by scripts/generate_thumbnails.py - do not edit by hand.\n"
        "// Maps each original R2 image URL to its pre-resized WebP thumbnail, both\n"
        "// produced by Pillow ahead of time (see storage.get_or_create_thumbnail).\n"
        f"window.THUMB_MAP = {json.dumps(thumb_map, indent=2, sort_keys=True)};\n",
        encoding="utf-8",
    )
    print(f"\nWrote {len(thumb_map)} entries to {OUT_PATH.relative_to(ROOT)}")
    if failures:
        print(f"{len(failures)} URL(s) failed and were left out of the map:", file=sys.stderr)
        for url in failures:
            print(f"  {url}", file=sys.stderr)


if __name__ == "__main__":
    main()
